spring.application.name=Demo
cloud.aws.region.static =ap-south-2
aws.bucket.name =ldms-prod-storage

spring.data.mongodb.uri=${MONGODB_URI}

spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
