name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build Project
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: mvn clean package -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ec2-user/demo"

      - name: Restart Application
        uses: appleboy/ssh-action@v1.2.0
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: MONGODB_URI
          script: |
            pkill -f "Demo-0.0.1-SNAPSHOT.jar" || true
            sleep 5

            cd /home/ec2-user/demo

            nohup java -jar Demo-0.0.1-SNAPSHOT.jar > /home/ec2-user/app.log 2>&1 &

            sleep 10

            ps -ef | grep java
            tail -50 /home/ec2-user/app.log
